// Dane demonstracyjne: sklepy, kategorie i produkty.
// W wersji produkcyjnej ten plik zastepuje feed cenowy z API/afiliacji.
var STORES = {
    "Rossmann":   { c:"#E4032E", url:"https://www.rossmann.pl",     dl:"od 9,99 zł · darmowa od 99 zł" },
    "Hebe":       { c:"#00A9A7", url:"https://www.hebe.pl",         dl:"od 8,99 zł · darmowa od 99 zł" },
    "Notino":     { c:"#E5006D", url:"https://www.notino.pl",       dl:"od 9,90 zł · darmowa od 150 zł" },
    "Douglas":    { c:"#4A3A55", url:"https://www.douglas.pl",      dl:"od 12,90 zł · darmowa od 150 zł" },
    "Sephora":    { c:"#7A4CC9", url:"https://www.sephora.pl",      dl:"od 13,99 zł · darmowa od 200 zł" },
    "Superpharm": { c:"#0072CE", url:"https://www.superpharm.pl",   dl:"od 10,99 zł · darmowa od 129 zł" },
    "Ezebra":     { c:"#E09112", url:"https://www.ezebra.com.pl",   dl:"od 8,90 zł · darmowa od 99 zł" },
    "e.Leclerc":  { c:"#0068B4", url:"https://www.zakupy.leclerc",  dl:"odbiór w sklepie" }
  };

  var CATS = ["Wszystkie","Pielęgnacja twarzy","Makijaż","Pielęgnacja ciała","Włosy","Zapachy"];
  var GRAD = {
    "Pielęgnacja twarzy": ["#8B6BD9","#4A2E8F"],
    "Makijaż":            ["#C25AA8","#7A2E6B"],
    "Pielęgnacja ciała":  ["#5A8FD9","#2E4E8F"],
    "Włosy":              ["#6BB0C9","#2E6B8F"],
    "Zapachy":            ["#9A7ABF","#533A78"]
  };

  var P = [
    { brand:"La Roche-Posay", name:"Cicaplast Baume B5 balsam regenerujący", cat:"Pielęgnacja twarzy", vol:"40 ml", pop:98, rate:4.8, votes:2431,
      kw:"b5 cicaplast baume balsam regenerujacy kojacy",
      o:{ "Rossmann":{p:44.99}, "Hebe":{p:42.99,w:49.99}, "Notino":{p:39.90}, "Superpharm":{p:47.99}, "Douglas":{p:46.00} } },
    { brand:"La Roche-Posay", name:"Effaclar Duo(+) M krem przeciw niedoskonałościom", cat:"Pielęgnacja twarzy", vol:"40 ml", pop:91, rate:4.6, votes:1874,
      kw:"effaclar duo tradzik niedoskonalosci",
      o:{ "Rossmann":{p:74.99}, "Hebe":{p:72.99}, "Notino":{p:69.90}, "Superpharm":{p:79.99}, "Douglas":{p:78.00} } },
    { brand:"CeraVe", name:"Krem nawilżający do twarzy i ciała", cat:"Pielęgnacja twarzy", vol:"340 ml", pop:96, rate:4.7, votes:3102,
      kw:"cerave moisturising cream ceramidy sucha skora krem",
      o:{ "Rossmann":{p:54.99}, "Hebe":{p:59.99}, "Notino":{p:51.90}, "Superpharm":{p:62.50}, "Ezebra":{p:49.99} } },
    { brand:"CeraVe", name:"Pianka oczyszczająca do skóry normalnej i tłustej", cat:"Pielęgnacja twarzy", vol:"236 ml", pop:88, rate:4.5, votes:1560,
      kw:"cerave foaming cleanser pianka myjaca zel",
      o:{ "Rossmann":{p:47.99}, "Hebe":{p:44.99,w:52.99}, "Notino":{p:43.90}, "Superpharm":{p:49.99} } },
    { brand:"The Ordinary", name:"Niacinamide 10% + Zinc 1% serum", cat:"Pielęgnacja twarzy", vol:"30 ml", pop:94, rate:4.4, votes:4210,
      kw:"the ordinary niacynamid niacinamide cynk serum pory",
      o:{ "Notino":{p:34.90}, "Sephora":{p:39.00}, "Ezebra":{p:32.99}, "Douglas":{p:38.50} } },
    { brand:"The Ordinary", name:"Hyaluronic Acid 2% + B5 serum nawilżające", cat:"Pielęgnacja twarzy", vol:"30 ml", pop:87, rate:4.5, votes:2960,
      kw:"the ordinary kwas hialuronowy hyaluronic b5 serum",
      o:{ "Notino":{p:37.90}, "Sephora":{p:42.00}, "Ezebra":{p:35.99}, "Douglas":{p:41.00} } },
    { brand:"Paula's Choice", name:"Skin Perfecting 2% BHA płyn złuszczający", cat:"Pielęgnacja twarzy", vol:"118 ml", pop:85, rate:4.7, votes:1985,
      kw:"paulas choice bha kwas salicylowy peeling",
      o:{ "Notino":{p:149.00}, "Sephora":{p:159.00}, "Douglas":{p:155.00}, "Ezebra":{p:142.90} } },
    { brand:"Bioderma", name:"Sensibio H2O płyn micelarny", cat:"Pielęgnacja twarzy", vol:"500 ml", pop:90, rate:4.8, votes:5320,
      kw:"bioderma sensibio plyn micelarny demakijaz",
      o:{ "Rossmann":{p:64.99}, "Hebe":{p:62.99}, "Notino":{p:58.90}, "Superpharm":{p:69.99}, "Ezebra":{p:57.99} } },
    { brand:"Vichy", name:"Minéral 89 booster nawilżający", cat:"Pielęgnacja twarzy", vol:"50 ml", pop:83, rate:4.6, votes:2140,
      kw:"vichy mineral 89 booster kwas hialuronowy",
      o:{ "Rossmann":{p:89.99}, "Hebe":{p:84.99,w:99.99}, "Notino":{p:79.90}, "Superpharm":{p:94.99}, "Douglas":{p:92.00} } },
    { brand:"Pixi", name:"Glow Tonic tonik złuszczający", cat:"Pielęgnacja twarzy", vol:"250 ml", pop:76, rate:4.3, votes:1230,
      kw:"pixi glow tonic tonik kwas glikolowy",
      o:{ "Sephora":{p:79.00}, "Notino":{p:72.90}, "Douglas":{p:76.00} } },
    { brand:"Bielenda", name:"Neuro Retinol krem-koncentrat na noc", cat:"Pielęgnacja twarzy", vol:"50 ml", pop:74, rate:4.2, votes:890,
      kw:"bielenda neuro retinol krem noc zmarszczki",
      o:{ "Rossmann":{p:27.99}, "Hebe":{p:29.99}, "Superpharm":{p:32.99}, "Ezebra":{p:25.90} } },
    { brand:"Maybelline", name:"Lash Sensational tusz do rzęs", cat:"Makijaż", vol:"9,5 ml", pop:93, rate:4.5, votes:6120,
      kw:"maybelline lash sensational tusz mascara rzesy",
      o:{ "Rossmann":{p:44.99}, "Hebe":{p:42.99}, "Notino":{p:39.90}, "Superpharm":{p:47.99}, "Ezebra":{p:41.50} } },
    { brand:"L'Oréal Paris", name:"Infaillible 24H Fresh Wear podkład", cat:"Makijaż", vol:"30 ml", pop:89, rate:4.4, votes:3480,
      kw:"loreal infaillible fresh wear podklad kryjacy",
      o:{ "Rossmann":{p:59.99}, "Hebe":{p:57.99,w:64.99}, "Notino":{p:54.90}, "Superpharm":{p:64.99}, "Douglas":{p:62.00} } },
    { brand:"Rare Beauty", name:"Soft Pinch Liquid Blush róż w płynie", cat:"Makijaż", vol:"7,5 ml", pop:92, rate:4.8, votes:2890,
      kw:"rare beauty soft pinch roz blush plyn",
      o:{ "Sephora":{p:115.00}, "Notino":{p:119.00}, "Douglas":{p:112.90} } },
    { brand:"NYX", name:"Butter Gloss błyszczyk do ust", cat:"Makijaż", vol:"8 ml", pop:81, rate:4.3, votes:2210,
      kw:"nyx butter gloss blyszczyk usta",
      o:{ "Rossmann":{p:27.99}, "Hebe":{p:25.99,w:31.99}, "Notino":{p:23.90}, "Ezebra":{p:24.50}, "Douglas":{p:29.00} } },
    { brand:"Charlotte Tilbury", name:"Airbrush Flawless Setting Spray utrwalający", cat:"Makijaż", vol:"100 ml", pop:84, rate:4.6, votes:1670,
      kw:"charlotte tilbury airbrush setting spray utrwalacz",
      o:{ "Sephora":{p:189.00}, "Notino":{p:175.00}, "Douglas":{p:182.00} } },
    { brand:"Nivea", name:"Q10 balsam ujędrniający do ciała", cat:"Pielęgnacja ciała", vol:"400 ml", pop:78, rate:4.4, votes:1980,
      kw:"nivea q10 balsam ujedrniajacy cialo",
      o:{ "Rossmann":{p:32.99}, "Hebe":{p:34.99}, "Superpharm":{p:36.50}, "e.Leclerc":{p:29.90}, "Ezebra":{p:31.50} } },
    { brand:"Sol de Janeiro", name:"Brazilian Bum Bum krem do ciała", cat:"Pielęgnacja ciała", vol:"240 ml", pop:86, rate:4.7, votes:2310,
      kw:"sol de janeiro bum bum krem cialo",
      o:{ "Sephora":{p:189.00}, "Notino":{p:179.00}, "Douglas":{p:185.00} } },
    { brand:"CeraVe", name:"SA balsam wygładzający do ciała", cat:"Pielęgnacja ciała", vol:"473 ml", pop:79, rate:4.5, votes:1440,
      kw:"cerave sa smoothing balsam kwas salicylowy szorstka",
      o:{ "Rossmann":{p:69.99}, "Hebe":{p:67.99}, "Notino":{p:64.90}, "Superpharm":{p:74.99} } },
    { brand:"Olaplex", name:"No.3 Hair Perfector kuracja do włosów", cat:"Włosy", vol:"100 ml", pop:88, rate:4.6, votes:3670,
      kw:"olaplex no 3 hair perfector kuracja wlosy",
      o:{ "Notino":{p:99.90}, "Sephora":{p:115.00}, "Douglas":{p:109.00}, "Ezebra":{p:94.99} } },
    { brand:"Garnier", name:"Botanic Therapy odżywka Miód i Wosk", cat:"Włosy", vol:"200 ml", pop:72, rate:4.3, votes:1120,
      kw:"garnier botanic therapy odzywka miod wlosy",
      o:{ "Rossmann":{p:21.99}, "Hebe":{p:23.49}, "Superpharm":{p:24.99}, "e.Leclerc":{p:19.90}, "Ezebra":{p:20.50} } },
    { brand:"Lancôme", name:"La Vie Est Belle woda perfumowana", cat:"Zapachy", vol:"50 ml", pop:90, rate:4.7, votes:4550,
      kw:"lancome la vie est belle woda perfumowana edp perfumy",
      o:{ "Notino":{p:349.00}, "Douglas":{p:389.00}, "Sephora":{p:385.00}, "Ezebra":{p:329.00} } },
    { brand:"Yves Saint Laurent", name:"Libre woda perfumowana", cat:"Zapachy", vol:"50 ml", pop:87, rate:4.7, votes:3210,
      kw:"ysl yves saint laurent libre edp perfumy",
      o:{ "Notino":{p:379.00}, "Douglas":{p:419.00}, "Sephora":{p:415.00} } },
    { brand:"Dior", name:"Sauvage woda toaletowa", cat:"Zapachy", vol:"60 ml", pop:89, rate:4.8, votes:5890,
      kw:"dior sauvage edt perfumy meskie",
      o:{ "Notino":{p:359.00}, "Douglas":{p:399.00}, "Sephora":{p:395.00} } }
  ];
